export const groupTable = [
  {
    group: "Grupo A",
    members: [
      {
        name: "Qatar",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/QAT?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Ecuador",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/ECU?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Senegal",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/SEN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Países Bajos",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/NED?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo B",
    members: [
      {
        name: "Inglaterra",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/ENG?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Irán",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/IRN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Estados Unidos",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/USA?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Por definir",
        flag: "https://elcomercio.pe/resizer/CMBy5GAqgqFYqvWBHQFqMM58u7A=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/3RKS3OTR4BFUBIXJOKYADRE4AI.jpg",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo C",
    members: [
      {
        name: "Argentina",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/ARG?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Arabia Saudí",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/KSA?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "México",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/MEX?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Polonia",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/POL?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo D",
    members: [
      {
        name: "Francia",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/FRA?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Dinamarca",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/DEN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Túnez",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/TUN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Por definir",
        flag: "https://elcomercio.pe/resizer/CMBy5GAqgqFYqvWBHQFqMM58u7A=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/3RKS3OTR4BFUBIXJOKYADRE4AI.jpg",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo E",
    members: [
      {
        name: "España",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/ESP?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Alemania",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/GER?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Japón",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/JPN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Por definir",
        flag: "https://elcomercio.pe/resizer/CMBy5GAqgqFYqvWBHQFqMM58u7A=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/3RKS3OTR4BFUBIXJOKYADRE4AI.jpg",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo F",
    members: [
      {
        name: "Bélgica",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/BEL?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Canadá",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/CAN?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Marruecos",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/MAR?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Croacia",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/CRO?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo G",
    members: [
      {
        name: "Brasil",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/BRA?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Serbia",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/SRB?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Suiza",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/SUI?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Camerún",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/CMR?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
  {
    group: "Grupo H",
    members: [
      {
        name: "Portugal",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/POR?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Ghana",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/GHA?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "Uruguay",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/URU?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
      {
        name: "República de Corea",
        flag: "https://cloudinary.fifa.com/api/v1/picture/flags-sq-4/KOR?tx=c_fill,g_auto,q_auto,w_150",
        pj: 0,
        pg: 0,
        pe: 0,
        pp: 0,
        gf: 0,
        gc: 0,
        dif: 0,
        pts: 0,
      },
    ],
  },
];
